git clone --depth 1 https://github.com/dragonfireclient/killaura clientmods/killaura
git clone --depth 1 https://github.com/dragonfireclient/nametags clientmods/nametags
git clone --depth 1 https://github.com/dragonfireclient/autotool clientmods/autotool
git clone --depth 1 https://github.com/dragonfireclient/simpletp clientmods/simpletp
git clone --depth 1 https://github.com/dragonfireclient/karaoke clientmods/karaoke
git clone --depth 1 https://github.com/dragonfireclient/diglib clientmods/diglib
git clone --depth 1 https://github.com/dragonfireclient/digcustom clientmods/digcustom
git clone --depth 1 https://github.com/dragonfireclient/autokey clientmods/autokey
git clone --depth 1 https://github.com/dragonfireclient/draining clientmods/draining
git clone --depth 1 https://github.com/dragonfireclient/autoeat clientmods/autoeat
git clone --depth 1 https://github.com/dragonfireclient/autodupe clientmods/autodupe
git clone --depth 1 https://github.com/dragonfireclient/invutil clientmods/invutil
git clone --depth 1 https://github.com/dragonfireclient/crystalpvp clientmods/crystalpvp
git clone --depth 1 https://github.com/dragonfireclient/enderchest clientmods/enderchest
git clone --depth 1 https://github.com/dragonfireclient/worldutil clientmods/worldutil
git clone --depth 1 https://github.com/dragonfireclient/noweather clientmods/noweather
git clone --depth 1 https://github.com/dragonfireclient/physics_override clientmods/physics_override
git clone --depth 1 https://github.com/dragonfireclient/chateffects clientmods/chateffects
git clone --depth 1 https://github.com/dragonfireclient/bowaimbot clientmods/bowaimbot
git clone --depth 1 https://github.com/dragonfireclient/perlin clientmods/perlin
git clone --depth 1 https://github.com/dragonfireclient/warp clientmods/warp
git clone --depth 1 https://github.com/dragonfireclient/pathfinding clientmods/pathfinding
git clone --depth 1 https://github.com/Minetest-j45/protective_shell clientmods/protective_shell
git clone --depth 1 https://github.com/AFCMS/https://github.com/AFCMS/df_crypt_chat clientmods/df_crypth_chat
git clone --depth 1 https://github.com/Code-Sploit/df-mod-arrowblocker clientmods/df_mod_arrowblocker
git clone --depth 1 https://github.com/Code-Sploit/df-mod-fastbridge clientmods/df_mod_fastbridge
git clone --depth 1 https://github.com/Code-Sploit/df-mod-beddestroyer clientmods/df_mod_beddestroyer
git clone --depth 1 https://github.com/Code-Sploit/df-mod-automlg clientmods/df_mod_automlg
git clone --depth 1 https://github.com/Code-Sploit/df-mod-panic clientmods/df_mod_panic
git clone --depth 1 https://github.com/Code-Sploit/df-mod-locator clientmods/df_mod_locator
git clone --depth 1 https://github.com/Code-Sploit/df-mod-playertrapper clientmods/df_mod_playertrapper
git clone --depth 1 https://github.com/Code-Sploit/adv-cheat-gui clientmods/adv_cheat_gui
